services:
  web:
    container_name: snet_dev_web
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - api
      - postgres
  api:
    container_name: snet_dev_api
    restart: on-failure
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - DATABASE_URL=postgres://admin:posgres_password@postgres:5432/snet_db?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
  
  postgres:
    image: postgres:16
    container_name: snet_dev_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: posgres_password
      POSTGRES_DB: snet_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata_snet_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "snet_db"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s

volumes:
  pgdata_snet_dev: