services:
  api:
    container_name: snet_dev_api
    restart: on-failure
    build:
      context: ./server
    environment:
      - DATABASE_URL=postgres://admin:posgres_password@localhost:5432/snet_db?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  
  postgres:
    image: postgres:16
    container_name: snet_dev_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: posgres_password
      POSTGRES_DB: snet_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata_snet_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "snet_db"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s

volumes:
  pgdata_snet_dev: