FROM golang:1.24-alpine

WORKDIR /app

RUN apk add --no-cache git bash make postgresql-client

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go install github.com/air-verse/air@v1.62.0

EXPOSE 8080

CMD ["tail", "-f", "/dev/null"]
